// Generated by gencpp from file yolov8_msgs/Bb_vel.msg
// DO NOT EDIT!


#ifndef YOLOV8_MSGS_MESSAGE_BB_VEL_H
#define YOLOV8_MSGS_MESSAGE_BB_VEL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace yolov8_msgs
{
template <class ContainerAllocator>
struct Bb_vel_
{
  typedef Bb_vel_<ContainerAllocator> Type;

  Bb_vel_()
    : header()
    , id(0.0)
    , vel(0.0)  {
    }
  Bb_vel_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , id(0.0)
    , vel(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _id_type;
  _id_type id;

   typedef double _vel_type;
  _vel_type vel;





  typedef boost::shared_ptr< ::yolov8_msgs::Bb_vel_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yolov8_msgs::Bb_vel_<ContainerAllocator> const> ConstPtr;

}; // struct Bb_vel_

typedef ::yolov8_msgs::Bb_vel_<std::allocator<void> > Bb_vel;

typedef boost::shared_ptr< ::yolov8_msgs::Bb_vel > Bb_velPtr;
typedef boost::shared_ptr< ::yolov8_msgs::Bb_vel const> Bb_velConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yolov8_msgs::Bb_vel_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yolov8_msgs::Bb_vel_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::yolov8_msgs::Bb_vel_<ContainerAllocator1> & lhs, const ::yolov8_msgs::Bb_vel_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.id == rhs.id &&
    lhs.vel == rhs.vel;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::yolov8_msgs::Bb_vel_<ContainerAllocator1> & lhs, const ::yolov8_msgs::Bb_vel_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace yolov8_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::yolov8_msgs::Bb_vel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yolov8_msgs::Bb_vel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolov8_msgs::Bb_vel_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolov8_msgs::Bb_vel_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolov8_msgs::Bb_vel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolov8_msgs::Bb_vel_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yolov8_msgs::Bb_vel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d36faa96a33eaf5bde4b09cd5ead446f";
  }

  static const char* value(const ::yolov8_msgs::Bb_vel_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd36faa96a33eaf5bULL;
  static const uint64_t static_value2 = 0xde4b09cd5ead446fULL;
};

template<class ContainerAllocator>
struct DataType< ::yolov8_msgs::Bb_vel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yolov8_msgs/Bb_vel";
  }

  static const char* value(const ::yolov8_msgs::Bb_vel_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yolov8_msgs::Bb_vel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# vel\n"
"std_msgs/Header header\n"
"float64 id\n"
"float64 vel\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::yolov8_msgs::Bb_vel_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yolov8_msgs::Bb_vel_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.id);
      stream.next(m.vel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Bb_vel_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yolov8_msgs::Bb_vel_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yolov8_msgs::Bb_vel_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "id: ";
    Printer<double>::stream(s, indent + "  ", v.id);
    s << indent << "vel: ";
    Printer<double>::stream(s, indent + "  ", v.vel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YOLOV8_MSGS_MESSAGE_BB_VEL_H
