// Generated by gencpp from file yolov8_msgs/BoundingBox2D.msg
// DO NOT EDIT!


#ifndef YOLOV8_MSGS_MESSAGE_BOUNDINGBOX2D_H
#define YOLOV8_MSGS_MESSAGE_BOUNDINGBOX2D_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <yolov8_msgs/Pose2D.h>
#include <yolov8_msgs/Vector2.h>

namespace yolov8_msgs
{
template <class ContainerAllocator>
struct BoundingBox2D_
{
  typedef BoundingBox2D_<ContainerAllocator> Type;

  BoundingBox2D_()
    : center()
    , size()
    , id(0)  {
    }
  BoundingBox2D_(const ContainerAllocator& _alloc)
    : center(_alloc)
    , size(_alloc)
    , id(0)  {
  (void)_alloc;
    }



   typedef  ::yolov8_msgs::Pose2D_<ContainerAllocator>  _center_type;
  _center_type center;

   typedef  ::yolov8_msgs::Vector2_<ContainerAllocator>  _size_type;
  _size_type size;

   typedef int32_t _id_type;
  _id_type id;





  typedef boost::shared_ptr< ::yolov8_msgs::BoundingBox2D_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yolov8_msgs::BoundingBox2D_<ContainerAllocator> const> ConstPtr;

}; // struct BoundingBox2D_

typedef ::yolov8_msgs::BoundingBox2D_<std::allocator<void> > BoundingBox2D;

typedef boost::shared_ptr< ::yolov8_msgs::BoundingBox2D > BoundingBox2DPtr;
typedef boost::shared_ptr< ::yolov8_msgs::BoundingBox2D const> BoundingBox2DConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yolov8_msgs::BoundingBox2D_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yolov8_msgs::BoundingBox2D_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::yolov8_msgs::BoundingBox2D_<ContainerAllocator1> & lhs, const ::yolov8_msgs::BoundingBox2D_<ContainerAllocator2> & rhs)
{
  return lhs.center == rhs.center &&
    lhs.size == rhs.size &&
    lhs.id == rhs.id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::yolov8_msgs::BoundingBox2D_<ContainerAllocator1> & lhs, const ::yolov8_msgs::BoundingBox2D_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace yolov8_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::yolov8_msgs::BoundingBox2D_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yolov8_msgs::BoundingBox2D_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolov8_msgs::BoundingBox2D_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolov8_msgs::BoundingBox2D_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolov8_msgs::BoundingBox2D_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolov8_msgs::BoundingBox2D_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yolov8_msgs::BoundingBox2D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7a678d71f8998ae4690f9ad4663f405f";
  }

  static const char* value(const ::yolov8_msgs::BoundingBox2D_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7a678d71f8998ae4ULL;
  static const uint64_t static_value2 = 0x690f9ad4663f405fULL;
};

template<class ContainerAllocator>
struct DataType< ::yolov8_msgs::BoundingBox2D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yolov8_msgs/BoundingBox2D";
  }

  static const char* value(const ::yolov8_msgs::BoundingBox2D_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yolov8_msgs::BoundingBox2D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 2D position and orientation of the bounding box center\n"
"yolov8_msgs/Pose2D center\n"
"\n"
"# total size of the bounding box, in pixels, surrounding the object's center\n"
"yolov8_msgs/Vector2 size\n"
"\n"
"# id of the keypoint\n"
"int32 id\n"
"\n"
"================================================================================\n"
"MSG: yolov8_msgs/Pose2D\n"
"# 2D position in pixel coordinates\n"
"\n"
"yolov8_msgs/Point2D position\n"
"float64 theta\n"
"================================================================================\n"
"MSG: yolov8_msgs/Point2D\n"
"# 2D point in pixel coordinates\n"
"\n"
"float64 x\n"
"float64 y\n"
"================================================================================\n"
"MSG: yolov8_msgs/Vector2\n"
"# 2D size in pixel\n"
"\n"
"float64 x\n"
"float64 y\n"
;
  }

  static const char* value(const ::yolov8_msgs::BoundingBox2D_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yolov8_msgs::BoundingBox2D_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.center);
      stream.next(m.size);
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BoundingBox2D_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yolov8_msgs::BoundingBox2D_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yolov8_msgs::BoundingBox2D_<ContainerAllocator>& v)
  {
    s << indent << "center: ";
    s << std::endl;
    Printer< ::yolov8_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "  ", v.center);
    s << indent << "size: ";
    s << std::endl;
    Printer< ::yolov8_msgs::Vector2_<ContainerAllocator> >::stream(s, indent + "  ", v.size);
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YOLOV8_MSGS_MESSAGE_BOUNDINGBOX2D_H
