// Generated by gencpp from file map_manager/CheckCollisionResponse.msg
// DO NOT EDIT!


#ifndef MAP_MANAGER_MESSAGE_CHECKCOLLISIONRESPONSE_H
#define MAP_MANAGER_MESSAGE_CHECKCOLLISIONRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace map_manager
{
template <class ContainerAllocator>
struct CheckCollisionResponse_
{
  typedef CheckCollisionResponse_<ContainerAllocator> Type;

  CheckCollisionResponse_()
    : has_collision(false)  {
    }
  CheckCollisionResponse_(const ContainerAllocator& _alloc)
    : has_collision(false)  {
  (void)_alloc;
    }



   typedef uint8_t _has_collision_type;
  _has_collision_type has_collision;





  typedef boost::shared_ptr< ::map_manager::CheckCollisionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::map_manager::CheckCollisionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CheckCollisionResponse_

typedef ::map_manager::CheckCollisionResponse_<std::allocator<void> > CheckCollisionResponse;

typedef boost::shared_ptr< ::map_manager::CheckCollisionResponse > CheckCollisionResponsePtr;
typedef boost::shared_ptr< ::map_manager::CheckCollisionResponse const> CheckCollisionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::map_manager::CheckCollisionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::map_manager::CheckCollisionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::map_manager::CheckCollisionResponse_<ContainerAllocator1> & lhs, const ::map_manager::CheckCollisionResponse_<ContainerAllocator2> & rhs)
{
  return lhs.has_collision == rhs.has_collision;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::map_manager::CheckCollisionResponse_<ContainerAllocator1> & lhs, const ::map_manager::CheckCollisionResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace map_manager

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::map_manager::CheckCollisionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::map_manager::CheckCollisionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::map_manager::CheckCollisionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::map_manager::CheckCollisionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::map_manager::CheckCollisionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::map_manager::CheckCollisionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::map_manager::CheckCollisionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6314e54ac350a926e49f4f603eb76766";
  }

  static const char* value(const ::map_manager::CheckCollisionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6314e54ac350a926ULL;
  static const uint64_t static_value2 = 0xe49f4f603eb76766ULL;
};

template<class ContainerAllocator>
struct DataType< ::map_manager::CheckCollisionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "map_manager/CheckCollisionResponse";
  }

  static const char* value(const ::map_manager::CheckCollisionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::map_manager::CheckCollisionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool has_collision\n"
;
  }

  static const char* value(const ::map_manager::CheckCollisionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::map_manager::CheckCollisionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.has_collision);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CheckCollisionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::map_manager::CheckCollisionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::map_manager::CheckCollisionResponse_<ContainerAllocator>& v)
  {
    s << indent << "has_collision: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.has_collision);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAP_MANAGER_MESSAGE_CHECKCOLLISIONRESPONSE_H
