// Generated by gencpp from file map_manager/RandomSample.msg
// DO NOT EDIT!


#ifndef MAP_MANAGER_MESSAGE_RANDOMSAMPLE_H
#define MAP_MANAGER_MESSAGE_RANDOMSAMPLE_H

#include <ros/service_traits.h>


#include <map_manager/RandomSampleRequest.h>
#include <map_manager/RandomSampleResponse.h>


namespace map_manager
{

struct RandomSample
{

typedef RandomSampleRequest Request;
typedef RandomSampleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RandomSample
} // namespace map_manager


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::map_manager::RandomSample > {
  static const char* value()
  {
    return "498b6ea7d13c53a4744bbed23ba7fed1";
  }

  static const char* value(const ::map_manager::RandomSample&) { return value(); }
};

template<>
struct DataType< ::map_manager::RandomSample > {
  static const char* value()
  {
    return "map_manager/RandomSample";
  }

  static const char* value(const ::map_manager::RandomSample&) { return value(); }
};


// service_traits::MD5Sum< ::map_manager::RandomSampleRequest> should match
// service_traits::MD5Sum< ::map_manager::RandomSample >
template<>
struct MD5Sum< ::map_manager::RandomSampleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::map_manager::RandomSample >::value();
  }
  static const char* value(const ::map_manager::RandomSampleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::map_manager::RandomSampleRequest> should match
// service_traits::DataType< ::map_manager::RandomSample >
template<>
struct DataType< ::map_manager::RandomSampleRequest>
{
  static const char* value()
  {
    return DataType< ::map_manager::RandomSample >::value();
  }
  static const char* value(const ::map_manager::RandomSampleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::map_manager::RandomSampleResponse> should match
// service_traits::MD5Sum< ::map_manager::RandomSample >
template<>
struct MD5Sum< ::map_manager::RandomSampleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::map_manager::RandomSample >::value();
  }
  static const char* value(const ::map_manager::RandomSampleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::map_manager::RandomSampleResponse> should match
// service_traits::DataType< ::map_manager::RandomSample >
template<>
struct DataType< ::map_manager::RandomSampleResponse>
{
  static const char* value()
  {
    return DataType< ::map_manager::RandomSample >::value();
  }
  static const char* value(const ::map_manager::RandomSampleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAP_MANAGER_MESSAGE_RANDOMSAMPLE_H
