(cl:defpackage map_manager-srv
  (:use )
  (:export
   "CHECKCOLLISION"
   "<CHECKCOLLISION-REQUEST>"
   "CHECKCOLLISION-REQUEST"
   "<CHECKCOLLISION-RESPONSE>"
   "CHECKCOLLISION-RESPONSE"
   "RANDOMSAMPLE"
   "<RANDOMSAMPLE-REQUEST>"
   "RANDOMSAMPLE-REQUEST"
   "<RANDOMSAMPLE-RESPONSE>"
   "RANDOMSAMPLE-RESPONSE"
  ))

